version: "3" 
# docker compose up -d
# docker compose down
# docker-compose logs -f police_nodejs
# docker-compose ps
# docker-compose build --no-cache
# NodeServer: http://127.0.0.1:3000/uechat
# MySqlDatabase: http://localhost:8083/

networks:
  mysql-phpmyadmin:
    name: mysql-phpmyadmin
    # use the bridge driver
    driver: bridge

volumes:
  mysqldata:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "${FOLDER_MYSQL}"
  nodeapp:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "${FOLDER_NODEAPP}"

services:
  police_mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "6033:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      mysql-phpmyadmin:
        aliases:
          - mysql

  police_phpmyadmin:
    image: phpmyadmin:5.2.0
    container_name: phpmyadmin
    links:
      - police_mysql
    environment:
      PMA_HOST: ${PMA_HOST}
      PMA_PORT: ${PMA_PORT}
    ports:
      - 8083:80
    networks:
      mysql-phpmyadmin:
        aliases:
          - phpmyadmin
  police_nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    environment:
      PORT: ${PORT}
      ENV: ${ENV}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3000:3000"
    depends_on:
      - police_mysql
    volumes:
      - nodeapp:/home/node/app
    networks:
      mysql-phpmyadmin:
        aliases:
          - mysql
