version: "3" 
# docker compose up -d
# docker compose down
# docker-compose logs -f police_nodejs
# docker-compose ps
# docker-compose build --no-cache
# docker images
# docker port police_nodejs
# docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' police_nodejs
# docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' mysql
# NodeServer: http://127.0.0.1:3000/uechat
# MySqlDatabase: http://localhost:8083/
# ssh root@<your_IP_address>

networks:
  mysql-phpmyadmin:
    name: mysql-phpmyadmin
    # use the bridge driver
    driver: bridge

volumes:
  mysqldata:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "${FOLDER_MYSQL}"
  nodeapp:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "${FOLDER_NODEAPP}"

services:
  police_mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "6033:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      mysql-phpmyadmin:
        aliases:
          - police_mysql

  police_phpmyadmin:
    image: phpmyadmin:5.2.0
    container_name: phpmyadmin
    links:
      - police_mysql
    environment:
      PMA_HOST: ${PMA_HOST}
      PMA_PORT: ${PMA_PORT}
    ports:
      - 8083:80
    networks:
      mysql-phpmyadmin:
        aliases:
          - police_phpmyadmin
  
  police_nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: police_nodejs
    links:
      - police_mysql
    restart: unless-stopped
    environment:
      PMA_HOST: ${PMA_HOST}
      PMA_PORT: ${PMA_PORT}
      PORT: ${PORT}
      ENV: ${ENV}
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8081:3000"
      - "2222:22"
    depends_on:
      - mysql
    volumes:
      - nodeapp:/home/node/app
    networks:
      mysql-phpmyadmin:
        aliases:
          - police_nodejs
